version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ğŸ‘· workflows:"
    schedule:
      interval: daily
    assignees:
      - "jeremmfr"
  - package-ecosystem: gomod
    directory: /
    commit-message:
      prefix: "â¬†ï¸ deps:"
    schedule:
      interval: daily
    assignees:
      - "jeremmfr"
